/////////////////////////////////////////////////////////////
//                                                         //
//   WARNUNG, dies Datei wird automatisch durch            //
//   das Program "Convert_Unit_to_pas_includes" erzeugt !  //
//   Erzeugt am: 28-08-2024   16:44                        //
//                                                         //
/////////////////////////////////////////////////////////////

{$IFDEF read_interface}

function g_spaced_primes_closest(num: Tguint): Tguint; cdecl; external libglib2;

// === Konventiert am: 11-8-24 19:32:56 ===


{$ENDIF read_interface}


{$IFDEF read_implementation}



{$ENDIF read_implementation}
