unit va_enumtypes;

interface

uses
  glib280, gst124;

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{ This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses.  }
(** unsupported pragma#pragma once*)
{$include <glib-object.h>}
{$include <gst/va/va-prelude.h>}
{ enumerations from "gstva.h"  }

function gst_va_feature_get_type:TGType;cdecl;external libgstvap;
{ Generated data ends here  }

// === Konventiert am: 8-10-24 16:14:31 ===

function GST_TYPE_VA_FEATURE : TGType;

implementation

function GST_TYPE_VA_FEATURE : TGType;
  begin
    GST_TYPE_VA_FEATURE:=gst_va_feature_get_type;
  end;



end.
