/////////////////////////////////////////////////////////////
//                                                         //
//   WARNUNG, dies Datei wird automatisch durch            //
//   das Program "Convert_Unit_to_pas_includes" erzeugt !  //
//   Erzeugt am: 23-08-2024   18:15                        //
//                                                         //
/////////////////////////////////////////////////////////////

{$IFDEF read_interface}

procedure g_source_set_closure(Source: PGSource; closure: PGClosure); cdecl; external libgobject2_0;
procedure g_source_set_dummy_callback(Source: PGSource); cdecl; external libgobject2_0;

// === Konventiert am: 15-8-24 19:51:31 ===


{$ENDIF read_interface}


{$IFDEF read_implementation}



{$ENDIF read_implementation}
